### ISSUE TITLE
BRo

### ISSUE THREAD

**Issue by ghkkhan** [ghkkhan/Sound-Sharer#2]
BRo? what is going on with that 10,000 line long socket.io js file?
I feel like that's not the right way to do it!

**Comment by ianhudson87** [comment]
I will try and make 10,000 files, each with 1 line of code

https://stackoverflow.com/questions/23653617/socket-io-listen-events-in-separate-files-in-node-js

**Comment by ghkkhan** [comment]
Sounds like a plan!

I'm marking this issue :100:
